[package]
authors = ["ZhangChao <jerry4718@qq.com>"]
edition = "2021"
name = "napi-blitz"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.8.2", features = ["napi6", "async"] }
napi-derive = "3.5.1"
taffy = "0.9.2"
lazy_static = "1.5.0"
style = { package = "stylo", version = "0.8" }
anyrender = "0.6.2"
anyrender_vello = "0.6.1"
winit = "0.30.12"
tokio = "1.48.0"

[dependencies.blitz]
version = "0.2.1"
features = []

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"